# Generated by Django 2.2.4 on 2020-01-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('oily', models.CharField(blank=True, max_length=1)),
                ('dry', models.CharField(blank=True, max_length=1)),
                ('sensitive', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageId', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('category', models.CharField(max_length=15)),
                ('ingredients', models.TextField()),
                ('monthlySales', models.IntegerField()),
                ('oily_score', models.IntegerField(default=0)),
                ('dry_score', models.IntegerField(default=0)),
                ('sensitive_score', models.IntegerField(default=0)),
                ('ingredientsList', models.ManyToManyField(related_name='product', to='item.Ingredient')),
            ],
        ),
    ]
