# Generated by Django 2.2.4 on 2020-01-20 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('oily', models.CharField(blank=True, max_length=1)),
                ('dry', models.CharField(blank=True, max_length=1)),
                ('sensitive', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageId', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('category', models.CharField(max_length=15)),
                ('ingredientsList', models.TextField()),
                ('monthlySales', models.IntegerField()),
                ('ingredients', models.ManyToManyField(to='item.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ProductScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oily_score', models.IntegerField()),
                ('dry_score', models.IntegerField()),
                ('sensitive_score', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Product')),
            ],
        ),
    ]
