# Generated by Django 2.2.4 on 2020-01-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='product', to='item.Ingredient'),
        ),
        migrations.DeleteModel(
            name='ProductScore',
        ),
    ]
