# Generated by Django 2.2.4 on 2020-01-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200121_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dry_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='oily_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sensitive_score',
            field=models.IntegerField(default=0),
        ),
    ]
